Enum "document_status" {
  "ACTIVE"
  "INACTIVE"
}

Enum "project_status" {
  "ACTIVE"
  "INACTIVE"
}

Enum "user_role" {
  "ADMIN"
  "USER"
}

Enum "user_status" {
  "ACTIVE"
  "INACTIVE"
  "PENDING_REGISTRATION"
}

Table "kysely_migration" {
  "name" varchar(255) [pk, not null]
  "timestamp" varchar(255) [not null]
}

Table "kysely_migration_lock" {
  "id" varchar(255) [pk, not null]
  "is_locked" int4 [not null, default: 0]
}

Table "users" {
  "id" uuid [pk, not null]
  "email" text [not null]
  "password" text
  "created_at" timestamptz [not null, default: `CURRENT_TIMESTAMP`]
  "updated_at" timestamptz [not null, default: `CURRENT_TIMESTAMP`]
  "role" user_role [not null]
  "user_status" user_status [not null]
  "line_uid" text
}

Table "user_groups" {
  "id" uuid [pk, not null]
  "group_name" text [not null]
  "description" text [not null, default: '']
}

Table "user_group_users" {
  "id" uuid [pk, not null]
  "user_id" uuid [not null]
  "user_group_id" uuid
}

Table "projects" {
  "id" uuid [pk, not null]
  "project_name" text [not null]
  "project_description" text [not null, default: '']
  "project_guideline_md" text [not null, default: '']
  "project_status" project_status [not null]
  "created_at" timestamptz [not null, default: `CURRENT_TIMESTAMP`]
  "updated_at" timestamptz [not null, default: `CURRENT_TIMESTAMP`]
}

Table "user_group_projects" {
  "id" uuid [pk, not null]
  "project_id" uuid [not null]
  "user_group_id" uuid [not null]
}

Table "project_documents" {
  "id" uuid [pk, not null]
  "document_status" document_status [not null]
  "ai_summary_md" text [not null, default: '']
}

Table "project_ai_summaries" {
  "id" uuid [pk, not null]
  "created_at" timestamptz [not null, default: `CURRENT_TIMESTAMP`]
  "project_id" uuid [not null]
  "ai_summary_md" text [not null, default: '']
}

Table "stored_files" {
  "id" uuid [pk, not null]
  "ref_name" text [not null]
  "key_path" text [not null]
  "owner_table" text [not null]
  "owner_id" uuid [not null]
  "filename" text [not null]
  "filesize_byte" int8 [not null]
  "storage_name" text [not null, default: 's3']
  "presign_url" text [not null]
  "is_public" bool [not null, default: false]
  "created_at" timestamptz [not null, default: `CURRENT_TIMESTAMP`]
  "updated_at" timestamptz [not null, default: `CURRENT_TIMESTAMP`]
  "mime_type" text [not null]
  "extension" text [not null]
  "checksum" text [not null]
  "expire_at" timestamptz

  Indexes {
    (ref_name, owner_table, owner_id) [type: btree, name: "stored_files_ref_owner_idx"]
  }
}

Ref "project_ai_summaries_project_id_fkey":"projects"."id" < "project_ai_summaries"."project_id" [delete: cascade]

Ref "user_group_projects_project_id_fkey":"projects"."id" < "user_group_projects"."project_id" [delete: cascade]

Ref "user_group_projects_user_group_id_fkey":"user_groups"."id" < "user_group_projects"."user_group_id" [delete: cascade]

Ref "user_group_users_user_group_id_fkey":"user_groups"."id" < "user_group_users"."user_group_id" [delete: cascade]

Ref "user_group_users_user_id_fkey":"users"."id" < "user_group_users"."user_id" [delete: cascade]
