/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ActionType = "CREATE" | "DELETE" | "UPDATE";

export type ActorType = "SYSTEM" | "USER";

export type ChatSender = "BOT" | "USER";

export type DocumentStatus = "ACTIVE" | "INACTIVE";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type ProjectStatus = "ACTIVE" | "INACTIVE";

export type UserRole = "ADMIN" | "USER";

export type UserStatus = "ACTIVE" | "INACTIVE" | "PENDING_REGISTRATION";

export interface AuditLogs {
  action_detail: Generated<string>;
  action_type: Generated<ActionType>;
  actor_type: Generated<ActorType>;
  created_at: Generated<string>;
  created_by_id: string | null;
  id: string;
  owner_id: string;
  owner_table: string;
  raw_data: Json;
}

export interface LineAccounts {
  active_line_session_id: string | null;
  created_at: Generated<string>;
  id: string;
}

export interface LineChatLogs {
  chat_sender: ChatSender;
  created_at: Generated<string>;
  id: string;
  line_session_id: string;
  message: string;
  parent_id: string | null;
}

export interface LineSessions {
  created_at: Generated<string>;
  id: string;
  latest_chat_log_id: string | null;
  line_account_id: string;
  project_id: string;
  updated_at: Generated<string>;
}

export interface ProjectChats {
  chat_sender: ChatSender;
  created_at: Generated<string>;
  id: string;
  message: string;
  parent_id: string | null;
  project_id: string;
  user_id: string;
}

export interface ProjectDocuments {
  ai_summary_md: Generated<string>;
  created_at: Generated<string>;
  document_details: Generated<string>;
  document_status: DocumentStatus;
  id: string;
  project_id: string;
}

export interface Projects {
  ai_summary_md: Generated<string>;
  created_at: Generated<string>;
  id: string;
  project_description: Generated<string>;
  project_guideline_md: Generated<string>;
  project_name: string;
  project_status: ProjectStatus;
  updated_at: Generated<string>;
}

export interface StoredFiles {
  checksum: string | null;
  created_at: Generated<string>;
  expire_at: string | null;
  extension: string;
  filename: string;
  filesize_byte: string;
  id: string;
  is_public: Generated<boolean>;
  key_path: string;
  mime_type: string;
  owner_id: string;
  owner_table: string;
  presign_url: string;
  ref_name: string;
  storage_name: Generated<string>;
  updated_at: Generated<string>;
}

export interface UserGroupProjects {
  project_id: string;
  user_group_id: string;
}

export interface UserGroups {
  created_at: Generated<string>;
  description: Generated<string>;
  group_name: string;
  id: string;
  updated_at: Generated<string>;
}

export interface UserGroupUsers {
  user_group_id: string;
  user_id: string;
}

export interface UserManageProjects {
  created_at: Generated<string>;
  project_id: string;
  user_id: string;
}

export interface UserOtps {
  created_at: Generated<string>;
  expire_at: string;
  id: string;
  user_id: string;
}

export interface Users {
  created_at: Generated<string>;
  email: string;
  first_name: string;
  id: string;
  last_name: string;
  last_signed_in_at: string | null;
  line_account_id: string | null;
  password: string | null;
  role: UserRole;
  updated_at: Generated<string>;
  user_status: UserStatus;
}

export interface DB {
  audit_logs: AuditLogs;
  line_accounts: LineAccounts;
  line_chat_logs: LineChatLogs;
  line_sessions: LineSessions;
  project_chats: ProjectChats;
  project_documents: ProjectDocuments;
  projects: Projects;
  stored_files: StoredFiles;
  user_group_projects: UserGroupProjects;
  user_group_users: UserGroupUsers;
  user_groups: UserGroups;
  user_manage_projects: UserManageProjects;
  user_otps: UserOtps;
  users: Users;
}
