/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ActionType = "CREATE" | "DELETE" | "UPDATE";

export type ActorType = "SYSTEM" | "USER";

export type AiUsageAction = "CHAT_LINE" | "CHAT_PROJECT" | "GENERATE_PROJECT_DOCUMENT_SUMMARY" | "GENERATE_PROJECT_SUMMARY";

export type ChatSender = "BOT" | "USER";

export type DocumentStatus = "ACTIVE" | "INACTIVE" | "PROCESSING";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LineSessionStatus = "ACTIVE" | "INACTIVE";

export type MessageStatus = "DEAD" | "FAIL" | "INVALID_PAYLOAD" | "SUCCESS";

export type ProjectStatus = "ACTIVE" | "INACTIVE" | "PROCESSING";

export type UserRole = "ADMIN" | "MANAGER" | "USER";

export type UserStatus = "ACTIVE" | "INACTIVE" | "PENDING_REGISTRATION";

export interface AiUsages {
  ai_reply_at: string | null;
  ai_request_at: string;
  ai_usage_action: AiUsageAction;
  confidence: number;
  created_at: Generated<string>;
  id: string;
  project_id: string;
  ref_id: string;
  ref_table: string;
  reply_time_ms: number | null;
  token_used: number;
  user_id: string | null;
}

export interface AuditLogs {
  action_detail: Generated<string>;
  action_type: Generated<ActionType>;
  actor_type: Generated<ActorType>;
  created_at: Generated<string>;
  created_by_id: string | null;
  id: string;
  owner_id: string;
  owner_table: string;
  raw_data: Json;
}

export interface LineAccounts {
  created_at: Generated<string>;
  id: string;
}

export interface LineBots {
  channel_access_token: string;
  channel_secret: string;
  created_at: Generated<string>;
  id: string;
  updated_at: Generated<string>;
}

export interface LineChatLogs {
  chat_sender: ChatSender;
  created_at: Generated<string>;
  id: string;
  line_account_id: string;
  line_session_id: string | null;
  message: string;
  parent_id: string | null;
}

export interface LineSessions {
  created_at: Generated<string>;
  id: string;
  latest_chat_log_id: string | null;
  line_account_id: string;
  line_bot_id: string;
  line_session_status: Generated<LineSessionStatus>;
  project_id: string;
  updated_at: Generated<string>;
}

export interface MessageTasks {
  attempts: Generated<number>;
  created_at: Generated<string>;
  exchange_name: string;
  expire_at: string;
  id: string;
  last_error: string | null;
  max_attempts: Generated<number>;
  message_status: MessageStatus;
  payload: Json;
  queue_name: string;
  updated_at: Generated<string>;
}

export interface PasswordResetTokens {
  created_at: Generated<string>;
  expire_at: string;
  id: string;
  revoke_at: string | null;
  token_hash: string;
  user_id: string;
}

export interface ProjectChatLogs {
  chat_sender: ChatSender;
  created_at: Generated<string>;
  id: string;
  message: string;
  parent_id: string | null;
  project_chat_session_id: string;
}

export interface ProjectChatSessions {
  created_at: Generated<string>;
  id: string;
  latest_chat_log_id: string | null;
  project_id: string;
  user_id: string;
}

export interface ProjectDocuments {
  ai_summary_md: Generated<string>;
  created_at: Generated<string>;
  created_by_id: string | null;
  document_details: Generated<string>;
  document_status: DocumentStatus;
  id: string;
  is_require_regenerate: Generated<boolean>;
  project_id: string;
  updated_at: Generated<string>;
  updated_by_id: string | null;
}

export interface Projects {
  ai_summary_md: Generated<string>;
  created_at: Generated<string>;
  created_by_id: string | null;
  id: string;
  is_require_regenerate: Generated<boolean>;
  project_description: Generated<string>;
  project_guideline_md: Generated<string>;
  project_name: string;
  project_status: ProjectStatus;
  updated_at: Generated<string>;
  updated_by_id: string | null;
}

export interface Sessions {
  created_at: Generated<string>;
  device_uid: string;
  expire_at: string;
  id: string;
  info: Json;
  revoke_at: string | null;
  token_hash: string;
  user_id: string;
}

export interface StoredFiles {
  checksum: string | null;
  created_at: Generated<string>;
  expire_at: string | null;
  extension: string;
  filename: string;
  filesize_byte: string;
  id: string;
  is_public: Generated<boolean>;
  key_path: string;
  mime_type: string;
  owner_id: string;
  owner_table: string;
  presign_url: string;
  ref_name: string;
  storage_name: Generated<string>;
  updated_at: Generated<string>;
}

export interface UserGroupManagers {
  user_group_id: string;
  user_id: string;
}

export interface UserGroupProjects {
  project_id: string;
  user_group_id: string;
}

export interface UserGroups {
  created_at: Generated<string>;
  created_by_id: string | null;
  description: Generated<string>;
  group_name: string;
  id: string;
  updated_at: Generated<string>;
  updated_by_id: string | null;
}

export interface UserGroupUsers {
  user_group_id: string;
  user_id: string;
}

export interface UserManageProjects {
  created_at: Generated<string>;
  project_id: string;
  user_id: string;
}

export interface Users {
  created_at: Generated<string>;
  created_by_id: string | null;
  email: string;
  first_name: string;
  id: string;
  last_name: string;
  last_signed_in_at: string | null;
  line_account_id: string | null;
  password: string | null;
  role: UserRole;
  updated_at: Generated<string>;
  updated_by_id: string | null;
  user_status: UserStatus;
}

export interface UserVerifications {
  code: string;
  created_at: Generated<string>;
  expire_at: string;
  id: string;
  revoke_at: string | null;
  user_id: string;
}

export interface DB {
  ai_usages: AiUsages;
  audit_logs: AuditLogs;
  line_accounts: LineAccounts;
  line_bots: LineBots;
  line_chat_logs: LineChatLogs;
  line_sessions: LineSessions;
  message_tasks: MessageTasks;
  password_reset_tokens: PasswordResetTokens;
  project_chat_logs: ProjectChatLogs;
  project_chat_sessions: ProjectChatSessions;
  project_documents: ProjectDocuments;
  projects: Projects;
  sessions: Sessions;
  stored_files: StoredFiles;
  user_group_managers: UserGroupManagers;
  user_group_projects: UserGroupProjects;
  user_group_users: UserGroupUsers;
  user_groups: UserGroups;
  user_manage_projects: UserManageProjects;
  user_verifications: UserVerifications;
  users: Users;
}
